name: Secrets
# Run this workflow every time a new commit pushed to your repository.
on: workflow_dispatch
jobs:
  fetch_some_secrets:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
      - name: Fetch secrets from AKeyless
        id: fetch-secrets
        uses: cmancone/akeyless-action@v1.0.0
        with:
          access-id: p-qchvfq9ofg4z
          # we use a JSON string because Github actions don't support dictionaries as inputs
          static-secrets: '{"/Dev/Lab/SecretKey":"also_env_var_name"}'
          #dynamic-secrets: '{"/path/to/dynamic/secret":"another_output_name"}'
          # these are true by default, but left here for reference
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
      - name: Secret from Akeyless
        run: echo "${{ env.also_env_var_name }}"
